name: flash_briefs
description: "A new Flutter project."
publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.3.0-279.2.beta <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  json_annotation: ^4.8.1
  dio: ^5.4.0
  flutter_bloc: ^8.1.4
  freezed_annotation: ^2.4.1
  nested: ^1.0.0
  intl: ^0.19.0
  flutter_inappwebview: ^5.8.0
  html: ^0.15.4
  http: ^1.2.0
  google_generative_ai: ^0.2.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  freezed: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
